### ISSUE TITLE
Not correctly matching products

### ISSUE THREAD

**Issue by matthew-andrews** [Financial-Times/next-user-model#24]
I logged in as shilstonpremium@ft.com and had this in my cookie:

```
FT_P="exp=1443727091752&prod=71|72|74";
```

Whcih didn't match the `isSubscriber` regular expression and therefore didn't offer me an opt-in link.

I think the regular expression here will need to be:-

```
/FT_P="?[A-Za-z0-9=&|]*prod=([0-9=|]*);?/
```

(Add an `"?` after `FT_P=`)

cc @keirog @commuterjoy

**Comment by matthew-andrews** [comment]
I wonder if the format of the `FT_P` cookie has changed recently…

**Comment by matthew-andrews** [comment]
https://github.com/Financial-Times/next-user-model/pull/25

**Comment by keirog** [comment]
Fixed in PR above; closing
